// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["js/photos"], function(Photos) {
    var Blog;
    Blog = (function(_super) {

      __extends(Blog, _super);

      function Blog() {
        this.createButton = __bind(this.createButton, this);

        this.format = __bind(this.format, this);
        return Blog.__super__.constructor.apply(this, arguments);
      }

      Blog.prototype.format = function(data) {
        var post, _i, _len, _ref, _results;
        _ref = data.posts;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          post = _ref[_i];
          if (post.type === "regular") {
            _results.push(this.allPhotosArray.push({
              title: post["regular-title"],
              date: post.date,
              link: post.url
            }));
          } else {
            _results.push(void 0);
          }
        }
        return _results;
      };

      Blog.prototype.createButton = function(container) {
        var postTags;
        postTags = this.domEditor.createBlogPosts(this.allPhotosArray.slice(0, this.numOfPictures), "div", "title", "date", "link");
        return this.domEditor.injectInto(container, postTags);
      };

      return Blog;

    })(Photos);
    return Blog;
  });

}).call(this);
