// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  define(function() {
    var Gallery;
    Gallery = (function() {

      function Gallery(name) {
        this.name = name;
        this.hide = __bind(this.hide, this);

        this.display = __bind(this.display, this);

        this.setup = __bind(this.setup, this);

        this.element = null;
        this.navBar = "<div class='navHeader'><span class='backButton'><img src='./imgs/back.png'></span> \                <span class='forwardButton'><img src='./imgs/forward.png'></span>\                <span class='closeButton'><img src='imgs/close.png'></span></div>";
      }

      Gallery.prototype.setElement = function(newElement) {
        return this.element = newElement;
      };

      Gallery.prototype.getElement = function() {
        var elementCopy;
        return elementCopy = this.element;
      };

      Gallery.prototype.setup = function(tags) {
        this.element = $("<div id='" + this.name + "'/>");
        this.element.append($("" + this.navBar));
        return this.element.append(tags);
      };

      Gallery.prototype.display = function(newParent) {
        var _this = this;
        this.element.appendTo(newParent);
        this.element.addClass("centerGallery");
        return $('.closeButton').on('click', function() {
          return _this.hide();
        });
      };

      Gallery.prototype.hide = function() {
        return this.element.detach();
      };

      return Gallery;

    })();
    return Gallery;
  });

}).call(this);
