// Generated by CoffeeScript 1.4.0
(function() {
  var Gallery, Manipulater, PICTURES_TO_DISPLAY_ON_BUTTON, Photos, addPhotoButtonListener, addProjectButtonListener, domEditor, myPhotos, myProjects,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Manipulater = (function() {

    function Manipulater() {}

    Manipulater.prototype.createTags = function(anArray, tagType, key, attr) {
      var n, results, _i, _len;
      results = "";
      for (_i = 0, _len = anArray.length; _i < _len; _i++) {
        n = anArray[_i];
        results += "<" + tagType + " " + attr + "=" + n[key] + " >";
      }
      return results;
    };

    Manipulater.prototype.wrapTags = function(tagsToWrap, keyDataArray, tagType, key, attr) {
      var index, n, results, tagsArray, _i, _len;
      results = "";
      tagsArray = tagsToWrap.split(">");
      tagsArray.pop();
      for (index = _i = 0, _len = tagsArray.length; _i < _len; index = ++_i) {
        n = tagsArray[index];
        results += "<" + tagType + " " + attr + "='" + keyDataArray[index][key] + "'> " + n + "> </" + tagType + ">";
      }
      return results;
    };

    Manipulater.prototype.injectInto = function(parentDiv, elements) {
      return $("" + parentDiv).append(elements);
    };

    return Manipulater;

  })();

  Gallery = (function() {

    function Gallery(name) {
      this.name = name;
      this.hide = __bind(this.hide, this);

      this.display = __bind(this.display, this);

      this.setup = __bind(this.setup, this);

      this.element = null;
      this.navBar = "<div class='navHeader'><span class='backButton'><img src='./imgs/back.png'></span> \              <span class='forwardButton'><img src='./imgs/forward.png'></span>\              <span class='closeButton'><img src='imgs/close.png'></span></div>";
    }

    Gallery.prototype.setup = function(tags) {
      this.element = $("<div id='" + this.name + "'/>");
      this.element.append($("" + this.navBar));
      return this.element.append(tags);
    };

    Gallery.prototype.display = function(newParent) {
      var _this = this;
      this.element.appendTo(newParent);
      this.element.addClass("centerGallery");
      return $('.closeButton').on('click', function() {
        return _this.hide();
      });
    };

    Gallery.prototype.hide = function() {
      return this.element.detach();
    };

    return Gallery;

  })();

  Photos = (function() {

    function Photos(source) {
      this.source = source;
      this.createButton = __bind(this.createButton, this);

      this.cacheNextGallery = __bind(this.cacheNextGallery, this);

      this.get = __bind(this.get, this);

      this.format = __bind(this.format, this);

      this.currentSetStartNum = 0;
      this.NUM_TO_GET = 9;
      this.imgLinksRetrieved = false;
      this.photoArray = [];
      this.nextGalleryArray = [];
      this.url = ("http://" + this.source + "/api/read/json?num=") + this.NUM_TO_GET;
      this.gallery = new Gallery("photoGallery");
      this.galleryNext = new Gallery("photoGallery2");
    }

    Photos.prototype.format = function(data, photoArray) {
      var photo, photoArrays, post, _i, _j, _len, _len1, _ref, _ref1;
      photoArrays = [this.photoArray, this.nextGalleryArray];
      _ref = data.posts;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        post = _ref[_i];
        if (post.type === "photo") {
          if (post.photos.length === 0) {
            photoArrays[photoArray].push({
              tiny: post["photo-url-75"],
              small: post["photo-url-250"],
              big: post["photo-url-1280"]
            });
          } else {
            _ref1 = post.photos;
            for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
              photo = _ref1[_j];
              photoArrays[photoArray].push({
                tiny: photo["photo-url-75"],
                small: photo["photo-url-250"],
                big: photo["photo-url-1280"]
              });
            }
          }
        }
      }
      return this.imgLinksRetrieved = true;
    };

    Photos.prototype.get = function(startNum, photoArray, callBack) {
      var _this = this;
      if (startNum == null) {
        startNum = 0;
      }
      if (photoArray == null) {
        photoArray = 0;
      }
      if (startNum !== 0) {
        this.url = this.url + ("&start=" + startNum);
      }
      return $.ajax(this.url, {
        dataType: "jsonp",
        crossDomain: true,
        success: function(data) {
          _this.format(data, photoArray);
          if (callBack) {
            return callBack();
          }
        },
        error: function() {
          return console.log("error");
        }
      });
    };

    Photos.prototype.cacheNextGallery = function() {
      var _this = this;
      return this.get(this.currentSetStartNum + PICTURES_TO_DISPLAY_ON_BUTTON, 1, function() {
        var smallImgTags;
        smallImgTags = domEditor.createTags(_this.nextGalleryArray.slice(0, PICTURES_TO_DISPLAY_ON_BUTTON), "img", "small", "src");
        smallImgTags = domEditor.wrapTags(smallImgTags, _this.nextGalleryArray.slice(0, PICTURES_TO_DISPLAY_ON_BUTTON), "a", "href");
        _this.galleryNext.setup(smallImgTags);
        return $(".forwardButton").on("click", function(event) {
          _this.gallery.hide();
          return _this.galleryNext.display("body");
        });
      });
    };

    Photos.prototype.createButton = function(container, listener) {
      var smallImgTags, tinyImgTags;
      tinyImgTags = domEditor.createTags(this.photoArray.slice(0, PICTURES_TO_DISPLAY_ON_BUTTON), "img", "tiny", "src");
      domEditor.injectInto(container, tinyImgTags);
      listener();
      smallImgTags = domEditor.createTags(this.photoArray.slice(0, PICTURES_TO_DISPLAY_ON_BUTTON), "img", "small", "src");
      smallImgTags = domEditor.wrapTags(smallImgTags, this.photoArray.slice(0, PICTURES_TO_DISPLAY_ON_BUTTON), "a", "big", "href");
      return this.gallery.setup(smallImgTags);
    };

    return Photos;

  })();

  PICTURES_TO_DISPLAY_ON_BUTTON = 9;

  domEditor = new Manipulater();

  myPhotos = new Photos("wisechicken.tumblr.com");

  myProjects = new Photos("wpdprojects.tumblr.com");

  $.when(myPhotos.get()).done(function() {
    return myPhotos.createButton("#photoButton", addPhotoButtonListener);
  });

  $.when(myProjects.get()).done(function() {
    return myProjects.createButton('#projectsButton', addProjectButtonListener);
  });

  addPhotoButtonListener = function() {
    return $("#photoButton").on("click", function(event) {
      console.log("Photo Clicked");
      $("#photoButton > img").addClass("gallery");
      myPhotos.gallery.display("body");
      return myPhotos.cacheNextGallery();
    });
  };

  addProjectButtonListener = function() {
    return $("#projectsButton").on("click", function(event) {
      console.log("Photo Clicked");
      $("#photoButton > img").addClass("gallery");
      myProjects.gallery.display("body");
      return myProjects.cacheNextGallery();
    });
  };

}).call(this);
