// Generated by CoffeeScript 1.4.0
(function() {

  require(["js/blog", "js/manipulater", "js/photos", "js/projects"], function(Blog, Manipulater, Photos, Projects) {
    var PICTURES_TO_DISPLAY_ON_BUTTON, addPhotoButtonListener, addProjectButtonListener, domEditor, myBlogs, myPhotos, myProjects;
    PICTURES_TO_DISPLAY_ON_BUTTON = 9;
    domEditor = new Manipulater();
    myPhotos = new Photos("wisechicken.tumblr.com", PICTURES_TO_DISPLAY_ON_BUTTON);
    myProjects = new Projects("wpdprojects.tumblr.com", PICTURES_TO_DISPLAY_ON_BUTTON);
    myBlogs = Blog;
    $.when(myPhotos.get()).done(function() {
      return myPhotos.createButton("#photoButton", addPhotoButtonListener);
    });
    $.when(myProjects.get()).done(function() {
      return myProjects.createButton('#projectsButton', addProjectButtonListener);
    });
    addPhotoButtonListener = function() {
      return $("#photoButton").on("click", function(event) {
        console.log("Photo Clicked");
        $("#photoButton > img").addClass("gallery");
        myPhotos.gallery.display("body");
        return myPhotos.cacheNextGallery();
      });
    };
    return addProjectButtonListener = function() {
      return $("#projectsButton").on("click", function(event) {
        console.log("Photo Clicked");
        $("#photoButton > img").addClass("gallery");
        myProjects.gallery.display("body");
        return myProjects.cacheNextGallery();
      });
    };
  });

}).call(this);
