// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["js/photos"], function(Photos) {
    var Projects;
    Projects = (function(_super) {

      __extends(Projects, _super);

      function Projects() {
        return Projects.__super__.constructor.apply(this, arguments);
      }

      Projects.prototype.test = function() {
        return console.log(test);
      };

      return Projects;

    })(Photos);
    return Projects;
  });

}).call(this);
