// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["js/photos"], function(Photos) {
    var Projects;
    Projects = (function(_super) {

      __extends(Projects, _super);

      function Projects() {
        return Projects.__super__.constructor.apply(this, arguments);
      }

      Projects.prototype.setupGallery = function() {
        this.addTitle();
        return this.gallery.setup(this.smallImgTags);
      };

      Projects.prototype.addTitle = function() {
        var data, images, index, newImages, noCommas, _i, _len, _ref;
        images = this.smallImgTags.split('</a>');
        images.pop();
        _ref = this.currentGalleryArray;
        for (index = _i = 0, _len = _ref.length; _i < _len; index = ++_i) {
          data = _ref[index];
          images[index] = "<div> " + images[index] + ("</a> " + this.currentGalleryArray[index].caption + "</div>");
        }
        newImages = images.join();
        noCommas = newImages.replace(",", "");
        return this.smallImgTags = noCommas;
      };

      return Projects;

    })(Photos);
    return Projects;
  });

}).call(this);
